Repository thofma/Hecke.jl, pull requests merged in 2025-04, with the labels that each got.

#1830 Fix sum of trivial quadratic modules
  src/QuadForm/Quad/ZLattices.jl
  test/QuadForm/Quad/ZLattices.jl
Labels: release notes: not needed

#1842 chore: update changelog and bump version
  CHANGELOG.md
  Project.toml
Labels: release notes: not needed

#1835 Cleanup hom functions for `FinGenAbGrp` and `TorQuadModule`
  src/AlgAssAbsOrd/NEQ.jl
  src/AlgAssAbsOrd/PicardGroup.jl
  src/AlgAssRelOrd/NEQ.jl
  src/Deprecations.jl
  src/GrpAb/Dual.jl
  src/GrpAb/Map.jl
  src/NumFieldOrd/NfOrd/RayClassGrp.jl
  src/QuadForm/Torsion.jl
  src/RCF/autos.jl
  src/RCF/class_fields.jl
  src/RCF/conductor.jl
  src/RCF/rcf.jl
  src/RCF/rcf_stark.jl
  src/RCF/rcf_subfield.jl
  test/GrpAb/Map.jl
  test/QuadForm/Torsion.jl
Labels: breaking

#1844 Fix enumeration `ZZGenus` symbols
  src/QuadForm/Quad/ZGenus.jl
  test/QuadForm/Quad/ZGenus.jl
Labels: release notes: not needed

#1852 fix: rescaling of form in neighbour method
  src/QuadForm/Herm/GenusRep.jl
  test/QuadForm/Herm/GenusRep.jl
Labels: release notes: not needed, bugfix

#1855 chore: bump to 0.35.18
  Project.toml
Labels: release notes: not needed

#1856 chore: adjust changelog and bump version
  CHANGELOG.md
  Project.toml
Labels: release notes: not needed

#1858 Fix `local_factor` for Hermitian lattices
  src/QuadForm/Herm/Mass.jl
  test/QuadForm/Herm/Mass.jl
Labels: bug, release notes: use title

#1859 Fix order_type for generic non-simple absolute fields
  Project.toml
  src/NumField/NfAbs.jl
  src/NumFieldOrd/NfOrd/MaxOrd/MaxOrdNS.jl
Labels: bug, release notes: use title, topic: number fields

#1860 chore: bump version and add changelog
  CHANGELOG.md
  Project.toml
Labels: release notes: not needed

#1825 Add is_maximal & is_prime for some PIDIdeal subtypes
  src/Misc/PIDIdeal.jl
  src/NumField/NfAbs/Elem.jl
  src/NumField/QQ.jl
  test/Misc/PIDIdeal.jl
  test/NfAbs/Elem.jl
Labels: enhancement, release notes: use title
