Repository thofma/Hecke.jl, pull requests merged in 2025-05, with the labels that each got.

#1863 Performance improvements for orders and lattices
  src/AlgAss/AlgMatElem.jl
  src/AlgAssAbsOrd/Ideal.jl
  src/AlgAssAbsOrd/Order.jl
  src/AlgAssAbsOrd/PIP.jl
  src/AlgAssAbsOrd/PicardGroup.jl
  src/AlgAssAbsOrd/Quotient.jl
  src/GenOrd/Auxiliary.jl
  src/ModAlgAss/Lattices/Basics.jl
  src/ModAlgAss/ModAlgAss.jl
Labels: enhancement, release notes: use title, topic: algebras

#1800 Extend AA stub `isomorphism(::Type{<:Group}, ::Group)` to FinGenAbGroup
  src/GrpAb/GrpAbFinGen.jl
Labels: breaking

#1848 fix: add verification in sparse row constructor
  src/Sparse/Row.jl
  src/Sparse/ZZRow.jl
  test/Sparse/Row.jl
Labels: breaking

#1869 Move things from Oscar/MoveToHecke.jl
  src/EllCrv/EllCrv.jl
  src/Map/Map.jl
  src/Misc/FiniteField.jl
  src/Misc/Poly.jl
  src/QuadForm/Quad/ZLattices.jl
  src/Sparse/Row.jl
  test/EllCrv/EllCrv.jl
  test/Misc/FiniteField.jl
  test/Misc/Poly.jl
  test/Sparse/Row.jl
Labels: breaking, release notes: not needed

#1840 feat: overhaul printing of orders and ideals
  docs/src/howto/decompose.md
  docs/src/howto/defineorder.md
  docs/src/howto/reduction.md
  docs/src/manual/number_fields/class_fields.md
  docs/src/manual/number_fields/complex_embeddings.md
  docs/src/manual/orders/ideals.md
  docs/src/manual/orders/orders.md
  docs/src/manual/quad_forms/basics.md
  docs/src/manual/quad_forms/genusherm.md
  docs/src/manual/quad_forms/lattices.md
  src/Map/NumField.jl
  src/NumField/ComplexEmbeddings/Generic.jl
  src/NumField/ComplexEmbeddings/NfAbs.jl
  src/NumField/InfinitePlaces.jl
  src/NumField/NfRel/NfRel.jl
  src/NumField/NfRel/NfRelNS.jl
  src/NumFieldOrd/NfOrd/FracIdeal.jl
  src/NumFieldOrd/NfOrd/Ideal/Ideal.jl
  src/NumFieldOrd/NfOrd/LinearAlgebra.jl
  src/NumFieldOrd/NfOrd/NfOrd.jl
  src/NumFieldOrd/NfRelOrd/FracIdeal.jl
  src/NumFieldOrd/NfRelOrd/Ideal.jl
  src/NumFieldOrd/NfRelOrd/NfRelOrd.jl
  src/NumFieldOrd/NumFieldOrdElem.jl
  src/RCF/class_fields.jl
  test/NfOrd/FracIdl.jl
  test/NfOrd/Ideal.jl
Labels: breaking

#1865 Remove dependency on InteractiveUtils
  Project.toml
  examples/IsPower.jl
  src/AlgAss/Elem.jl
  src/Hecke.jl
Labels: breaking

#1872 chore: bump to 0.36.0
  Project.toml
Labels: release notes: not needed
