Repository thofma/Hecke.jl, pull requests merged in 2025-03, with the labels that each got.

#1794 Fix css for outdated doc warner
  docs/src/.vitepress/theme/style.css
Labels: bug, documentation, release notes: use title

#1795 Improvements for quaternion algebra (elements)
  src/AlgAss/AlgQuat.jl
  src/AlgAssAbsOrd/PIP/unit_group_generators.jl
  src/Deprecations.jl
  test/AlgAss/AlgQuat.jl
Labels: enhancement, release notes: use title, topic: algebras

#1799 Fix memory bug in sparse matrices over ZZ
  src/Sparse/ZZRow.jl
Labels: bug, release notes: not needed

#1792 Realign rational_reconstruction
  Project.toml
  examples/Det.jl
  src/Misc/RatRecon.jl
Labels: release notes: not needed

#1801 chore: add *swp to .gitignore
  .gitignore
Labels: release notes: not needed

#1802 Add `schur_index_over_center` for arbitrary algebras
  src/AlgAss/Ramification.jl
  src/exports.jl
  test/AlgAss/Ramification.jl
Labels: enhancement, release notes: use title, topic: algebras

#1804 chore: bump to 0.35.14
  Project.toml
Labels: release notes: not needed

#1806 chore: update changelog
  CHANGELOG.md
  dev/releases/release_notes.py
Labels: release notes: not needed

#1807 fix: unterminated jldoctest
  Project.toml
  src/NumField/Subfields.jl
Labels: release notes: not needed

#1808 chore: update changelog and bump version number
  CHANGELOG.md
  Project.toml
Labels: release notes: not needed

#1796 Add right divrem and right gcd for polynomial rings over noncommutative rings
  src/AlgAss/Elem.jl
  src/Misc/Poly.jl
  test/Misc/Poly.jl
Labels: enhancement, release notes: use title

#1809 Add `quaternion_algebra` constructor
  src/AlgAss/AlgQuat.jl
  src/exports.jl
  test/AlgAss/AlgQuat.jl
Labels: enhancement, release notes: use title, topic: algebras

#1822 Remove restriction in torsion unit computation
  src/NumFieldOrd/NfOrd/TorsionUnits.jl
  test/NfOrd/TorsionUnits.jl
Labels: enhancement, release notes: use title, topic: number fields

#1821 use element precision in small lift
  src/LocalField/Completions.jl
Labels: release notes: not needed

#1824 Improved torsion unit computation for cyclotomic fields
  src/NumFieldOrd/NfOrd/TorsionUnits.jl
  test/NfOrd/TorsionUnits.jl
Labels: enhancement, release notes: use title, topic: number fields

#1823 fix: progress bar for unconditional class group computation
  src/NumFieldOrd/NfOrd/Clgp/Proof.jl
Labels: release notes: not needed
